# WiFi credentials
WIFI_SSID = 'WIFINAME'
WIFI_PASS = 'WIFIPASS'

# Datacake credentials
SERIAL_NUMBER = '1234martin1234'
MQTT_BROKER = 'mqtt.datacake.co'
TOKEN = 'TOKEN'
PORT = 1883
HUMIDITY = 'HUMIDITY'
TEMPERATURE = 'TEMPERATURE'
